a = input('digite um valor: ')
print('O tipo primitivo desse valo é: ',type(a))
print('So tem espaço? ',a.isspace())
print('É um Numero? ', a.isnumeric())
print('É Alfabetico? ', a.isalpha())
print('É Alfanumerico? ', a.isalnum())
print('Esta em Maiusculo? ', a.upper())
print('Esta em Minusculo? ',a.lower())
print('Está Captalizada? ',a.istitle())
